apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-non-root4
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-all-containers-runAsNonRoot
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "All containers must set runAsNonRoot: true."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.runAsNonRoot }}"
                    operator: NotEquals
                    value: true
